-- FocusKid Supabase schema
-- Run this in the Supabase SQL editor.

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  name text not null,
  role text not null,
  email text not null,
  password_hash text,
  parent_id bigint references public.users(id) on delete set null,
  xp integer not null default 0,
  created_at timestamptz not null default now()
);

-- Make email unique per role and add parent_id for child accounts.
alter table public.users add column if not exists password_hash text;
alter table public.users add column if not exists parent_id bigint references public.users(id) on delete set null;
create unique index if not exists idx_users_email_role on public.users (email, role);
create index if not exists idx_users_parent_id on public.users (parent_id);

create table if not exists public.missions (
  id bigint generated by default as identity primary key,
  title text not null,
  time_minutes integer,
  parent_id bigint references public.users(id) on delete set null,
  file_path text,
  file_storage_path text,
  created_at timestamptz not null default now()
);

create table if not exists public.subtasks (
  id bigint generated by default as identity primary key,
  mission_id bigint not null references public.missions(id) on delete cascade,
  title text not null,
  completed boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.mission_files (
  id bigint generated by default as identity primary key,
  mission_id bigint not null references public.missions(id) on delete cascade,
  storage_path text not null,
  file_path text not null,
  original_name text not null,
  time_minutes integer,
  completed boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.mission_quizzes (
  id bigint generated by default as identity primary key,
  mission_id bigint not null references public.missions(id) on delete cascade,
  question text not null,
  option_a text not null,
  option_b text not null,
  option_c text not null,
  option_d text not null,
  correct_option text not null check (correct_option in ('A', 'B', 'C', 'D')),
  selected_option text,
  completed boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.reward_events (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  event_key text not null,
  xp integer not null,
  reason text not null,
  created_at timestamptz not null default now(),
  unique (user_id, event_key)
);

create index if not exists idx_subtasks_mission_id on public.subtasks (mission_id);
create index if not exists idx_mission_files_mission_id on public.mission_files (mission_id);
create index if not exists idx_mission_quizzes_mission_id on public.mission_quizzes (mission_id);
create index if not exists idx_reward_events_user_id on public.reward_events (user_id);
create index if not exists idx_missions_created_at on public.missions (created_at desc);

insert into storage.buckets (id, name, public)
values ('mission-files', 'mission-files', true)
on conflict (id) do update
set name = excluded.name,
    public = excluded.public;

create or replace function public.award_user_xp(
  target_user_id bigint,
  award_amount integer,
  award_reason text,
  award_event_key text
) returns jsonb
language plpgsql
as $$
declare
  normalized_xp integer := greatest(1, least(coalesce(award_amount, 0), 500));
  normalized_key text := left(coalesce(award_event_key, coalesce(award_reason, 'Reward') || ':' || extract(epoch from clock_timestamp())::text), 180);
  normalized_reason text := left(coalesce(award_reason, 'Reward'), 120);
  user_row public.users%rowtype;
  inserted_id bigint;
begin
  select * into user_row
  from public.users
  where id = target_user_id;

  if not found then
    return jsonb_build_object('awarded', false, 'xp', 0, 'reason', normalized_reason, 'event_key', normalized_key, 'user', null);
  end if;

  insert into public.reward_events (user_id, event_key, xp, reason)
  values (target_user_id, normalized_key, normalized_xp, normalized_reason)
  on conflict (user_id, event_key) do nothing
  returning id into inserted_id;

  if inserted_id is null then
    select * into user_row
    from public.users
    where id = target_user_id;

    return jsonb_build_object('awarded', false, 'xp', 0, 'reason', normalized_reason, 'event_key', normalized_key, 'user', to_jsonb(user_row));
  end if;

  update public.users
  set xp = coalesce(xp, 0) + normalized_xp
  where id = target_user_id
  returning * into user_row;

  return jsonb_build_object('awarded', true, 'xp', normalized_xp, 'reason', normalized_reason, 'event_key', normalized_key, 'user', to_jsonb(user_row));
end;
$$;

-- Focus session history: records each reading/focus session as metadata only.
create table if not exists public.focus_sessions (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  mission_id bigint references public.missions(id) on delete set null,
  file_id bigint references public.mission_files(id) on delete set null,
  planned_minutes integer not null default 15,
  started_at timestamptz not null default now(),
  ended_at timestamptz,
  completed boolean not null default false,
  distraction_count integer not null default 0
);

create index if not exists idx_focus_sessions_user_id on public.focus_sessions (user_id);
create index if not exists idx_focus_sessions_started_at on public.focus_sessions (started_at desc);

-- Distraction events: stores attention drift metadata, never camera/video data.
create table if not exists public.distraction_events (
  id bigint generated by default as identity primary key,
  session_id bigint references public.focus_sessions(id) on delete cascade,
  user_id bigint not null references public.users(id) on delete cascade,
  mission_id bigint references public.missions(id) on delete set null,
  file_id bigint references public.mission_files(id) on delete set null,
  reason text not null default 'attention_drift',
  created_at timestamptz not null default now()
);

create index if not exists idx_distraction_events_session_id on public.distraction_events (session_id);
create index if not exists idx_distraction_events_user_id on public.distraction_events (user_id);
create index if not exists idx_distraction_events_created_at on public.distraction_events (created_at desc);
